[package]
name = "slim-runner"
version = "0.1.6"
edition = "2024"
authors = ["Egor Lappo <elappo@stanford.edu>"]
description = "Run SLiM simulation grid runs in parallel"
readme = "README.md"
repository = "https://github.com/EgorLappo/slim-runner"
license = "GPL-3.0-or-later"

[dependencies]
indicatif-log-bridge = "0.2.3"
clap = { version = "4.6.7", features = ["derive"] }
indicatif = { version = "0.18.6", features = ["improved_unicode"] }
color-eyre = "0.6.5"
env_logger = "0.11.11"
itertools = "0.15.0"
log = "0.4.34"
polars = { version = "0.55.2", features = ["performant", "lazy", "parquet"] }
rand = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
crossbeam-channel = "0.5.17"
threadpool = "1.8.1"
steel-core = { version = "0.8.1", git = "https://github.com/mattwparas/steel.git", branch = "master" }
steel-derive = { version = "0.8.1", git = "https://github.com/mattwparas/steel.git", branch = "master" }
