[settings]
# global random seed
seed = 231
# number of replicates per parameter set
replicates = 10
# slim script to run
script = "example_script.slim"
# output directory
output_dir = "output"
# number of threads to use
cores = 6
# interval to write output to disk in parameter sets
write_every = 1000
# annotate the output log files with parameter values
annotate = true
# only run first `limit' simulations (for debugging purposes)
# limit = 100
# custom slim executable path (also can be set with $SLIM_EXE environment variable)
# slim_executable = "/usr/locl/bin/slim"

[grid]
N = [500, 1000, 2000, 5000]
s = { from = 0, to = 0.1, num = 11 }
h = { from = 0, to = 1, step = 0.25 }
mu = 10e-7
rbp = 10e-8
tag = "example"
